#!/usr/bin/env bash
#########################################################
# Created by jacknab for php-mpos and nomp pool...
# This script is intended to be run on Debian 11
# like this:
# curl https://raw.githubusercontent.com/jacknab/scripts/main/install.sh | bash
#
#########################################################
sudo apt-get install g++-mingw-w64-i686 mingw-w64-i686-dev g++-mingw-w64-x86-64 mingw-w64-x86-64-dev curl libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
git clone https://github.com/jacknab/MundoTeam_Core.git
cd /root/MundoTeam_Core
chmod +x autogen.sh
cd share
chmod +x genbuild.sh
cd ..
./autogen.sh
./configure --with-incompatible-bdb
make
make install
cd src
./mundoteamd -daemon
./mundoteam-cli createwallet default
./mundoteam-cli getnewaddress legacy > /MundoTeam_walletaddress_legacy.txt
./mundoteam-cli getnewaddress > /MundoTeam_walletaddress.txt

